# Generated by Django 5.0 on 2024-03-07 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('tenthmarks', models.CharField(max_length=10)),
                ('twelfthmarks', models.CharField(max_length=10)),
            ],
        ),
    ]
