# Generated by Django 5.0 on 2024-03-09 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FId', models.CharField(max_length=3)),
                ('FName', models.CharField(max_length=200)),
                ('FGender', models.CharField(max_length=10)),
                ('FEmail', models.EmailField(max_length=254)),
                ('FDesignation', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Faculty',
            },
        ),
    ]
