# Generated by Django 5.0 on 2024-03-03 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='courseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=10)),
                ('course_name', models.CharField(max_length=255)),
                ('offering_by', models.CharField(choices=[('CSE', 'CSE'), ('ECE', 'ECE'), ('AIDS', 'AIDS'), ('CSIT', 'CSIT'), ('BIO-TECH', 'BIO-TECH')], max_length=20)),
                ('offering_year', models.CharField(max_length=225)),
                ('credits', models.CharField(max_length=225)),
            ],
        ),
    ]
