# Generated by Django 5.0 on 2024-03-03 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultymodule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetails',
            old_name='course_id',
            new_name='courseid',
        ),
        migrations.RenameField(
            model_name='coursedetails',
            old_name='course_name',
            new_name='coursename',
        ),
        migrations.RenameField(
            model_name='coursedetails',
            old_name='offering_by',
            new_name='offeredby',
        ),
        migrations.RenameField(
            model_name='coursedetails',
            old_name='offering_year',
            new_name='offeringyear',
        ),
    ]
